In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
bankdata = pd.read_csv("./bill_authentication.csv")

In [8]:
X = bankdata.drop('Class', axis=1)
y = bankdata['Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [38]:
from sklearn.svm import SVC
svmclassifier = SVC(kernel='rbf')
svmclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
svmclassifier.intercept_

array([2.36580561])

In [42]:
svmclassifier.dual_coef_

array([[-1.        , -1.        , -0.51590065, -1.        , -1.        ,
        -1.        , -1.        , -0.70606819, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -0.55184369, -0.64496585, -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -0.28140983, -1.        , -0.50805732, -0.71403766,
        -1.        , -0.88994977, -0.86486387, -1.        , -1.        ,
        -1.        , -1.        ,  1.        ,  0.98702289,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  0.52351546,
         0.1865873 ,  1.        ,  0.89020891,  0.40414794,  0.69762366,
         0.82513756,  0.59783884,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1. 

In [36]:
svmclassifier.support_vectors_

array([[ 3.79800e-01,  7.09800e-01,  7.57200e-01, -4.44400e-01],
       [ 5.70600e-01, -2.48000e-02,  1.24210e+00, -5.62100e-01],
       [ 3.79800e-01,  7.09800e-01,  7.57200e-01, -4.44400e-01],
       [ 5.19500e-01, -3.26330e+00,  3.08950e+00, -9.84900e-01],
       [-7.86900e-01,  9.56630e+00, -3.78670e+00, -7.50340e+00],
       [ 3.29200e-01, -4.45520e+00,  4.57180e+00, -9.88800e-01],
       [ 5.70600e-01, -2.48000e-02,  1.24210e+00, -5.62100e-01],
       [ 5.70600e-01, -2.48000e-02,  1.24210e+00, -5.62100e-01],
       [ 3.29200e-01, -4.45520e+00,  4.57180e+00, -9.88800e-01],
       [ 3.29200e-01, -4.45520e+00,  4.57180e+00, -9.88800e-01],
       [-1.85840e+00,  7.88600e+00, -1.66430e+00, -1.83840e+00],
       [ 5.19470e-01, -3.26330e+00,  3.08950e+00, -9.84920e-01],
       [ 5.70600e-01, -2.48000e-02,  1.24210e+00, -5.62100e-01],
       [-1.85840e+00,  7.88600e+00, -1.66430e+00, -1.83840e+00],
       [ 5.70600e-01, -2.48410e-02,  1.24210e+00, -5.62080e-01],
       [ 3.79800e-01,  7.